# Generated by Django 4.1.7 on 2023-08-14 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vault'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaults_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
