# Generated by Django 4.1.7 on 2023-12-10 06:27

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_vault_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('keys', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
            ],
        ),
        migrations.AddField(
            model_name='vault',
            name='vault_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vault_content', to='core.vaulttype'),
        ),
    ]
