# Generated by Django 4.1.7 on 2023-12-10 06:35

import core.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_vaulttype_vault_vault_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaulttype',
            name='keys',
            field=core.base_models.ChoiceArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
    ]
