# Generated by Django 4.1.7 on 2023-12-10 06:37

import core.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_vaulttype_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaulttype',
            name='keys',
            field=core.base_models.ChoiceArrayField(base_field=models.CharField(choices=[('EMAIL', 'EMAIL'), ('USERNAME', 'USERNAME'), ('PASSWORD', 'PASSWORD'), ('URL', 'URL'), ('NOTES', 'NOTES'), ('TOKEN', 'TOKEN')], max_length=100), default=list, size=None),
        ),
    ]
